# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastlr <- function(X, y, tol = 1e-8, max_iter = 1000L) {
    .Call(`_fastlr_estimate_irls`, X, y, tol, max_iter)
}

